version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry install
      - poetry run pip install sphinx sphinx-rtd-theme

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - method: poetry
