
version: 2


build:
  # Install ubuntu 20.04
  os: ubuntu-20.04
  tools:
    # Install python 3.10
    python: "3.10"
    # Install poetry & project dependencies
  jobs:
    post_create_environment:
    - pip install poetry
    post_install:
    - poetry install


sphinx:
  configuration: docs/source/conf.py
