name: Automated test suite

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:

  test-python:

    runs-on: ubuntu-latest

    # Only run the action for the latest push
    # See https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:

      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry env use '3.10'
          poetry install

      - name: Run test scripts
        run: |
          poetry run pytest